divvun/gut

src/cli.rs
src/commands/mod.rs
src/commands/protected_branch.rs
src/github/rest.rs
src/main.rs

This is a command for create a protected branch with these config:
- enforce_admins: true
- required_linear_history: true
- allow-force-pushes: false
- allow-deletions: false

Create a protected branch

---

src/cli.rs
src/commands/create_team.rs
src/commands/mod.rs
src/github/rest.rs
src/main.rs

The new `create_team` works as follow:
`dadmin creat-team --organization divvun --team_name "new-team" -description "new team yes" --secret -members lenguyenthanh bbqsrc`

WIP: Create teams with members

---

src/cli.rs
src/commands/mod.rs
src/commands/protected_branch.rs
src/commands/set_team_permission.rs
src/github/rest.rs
src/main.rs

Add new set-permission command:
dadmin sp -o divvun -r a-regex -t a-new-team -p admin

Implement set permission command

---

src/commands/create_repo.rs
src/git/push.rs

Push only local branches

---

.clippy.toml
src/commands/create_repo.rs

Add override origin option for create repo command

---

src/commands/common.rs
src/commands/remove_repos.rs

Allow enter to abort remove repos command

---

src/commands/status.rs

Add added files column for status command

---

src/commands/clone.rs
src/commands/create.rs
src/commands/create_repo.rs
src/convert.rs
src/git/clone.rs
src/github/rest.rs
src/path.rs

Add clone option for create command

---

src/commands/apply.rs
src/commands/checkout.rs
src/commands/clean.rs
src/commands/commit.rs
src/commands/common.rs
src/commands/create_repo.rs
src/commands/fetch.rs
src/commands/merge.rs
src/commands/push.rs
src/commands/status.rs
src/convert.rs
src/filter.rs
src/path.rs

Fix error message when reading sub directories

---

src/commands/merge.rs
src/commands/set_info.rs

Just saw this because my editor pointed out the typo in homepage.
Also fixes one more typo.

Use structopt's `required_unless`

---

src/cli.rs
src/commands/mod.rs
src/commands/transfer.rs
src/github/rest.rs
src/main.rs

Implement transfer command

---

src/filter.rs

Fix caret symbol doesn't work in some command

---

Cargo.toml
src/commands/show_users.rs
src/github/graphql.rs
src/github/models.rs
src/github/rest.rs
user_query.graphql

Use GraphQl to query all users

---

src/commands/common.rs
src/commands/topic_helper.rs
src/github/models.rs

Sort Repos in alphabetical before processing

---

src/commands/hook.rs
src/commands/hook_create.rs
src/commands/hook_delete.rs
src/commands/mod.rs
src/github/rest.rs

Implement delete all hooks command

---

src/commands/status.rs

Show file status header at footer

---

Cargo.lock
Cargo.toml
list_dir.sh
src/commands/add.rs
src/commands/add_users.rs
src/commands/common.rs
src/commands/create.rs
src/commands/create_branch.rs
src/commands/push.rs
src/git/push.rs
src/git/status.rs

This update output of `create_branch` and `push` command. Also close #92

Better output color

---

Cargo.lock
Cargo.toml
src/commands/template/generate.rs
src/path.rs

Include ignore files when generate template

---

Cargo.lock
Cargo.toml
src/commands/pull.rs
src/commands/push.rs
src/git/fetch.rs
src/git/merge.rs
src/git/mod.rs
src/git/pull.rs
src/git/stash.rs

Stash before pull

---

Cargo.lock
Cargo.toml
src/commands/clone.rs
src/commands/create_branch.rs
src/commands/create_repo.rs
src/commands/pull.rs
src/commands/push.rs
src/commands/status.rs
src/convert.rs
src/git/clone.rs
src/git/models.rs

List of commands that are supported
- Pull
- Push
- Create branch
- Status
- Clone
Also close #145

Support asynchronous for some commands

---

src/commands/add_repos.rs
src/commands/apply.rs
src/commands/commit.rs
src/commands/common.rs
src/commands/topic_apply.rs

Better output and support asynchronous for 3 more commands

---

README.md

Both to help users, and to show off for curious people what gut can do.

Add help text to readme

---

Cargo.lock
Cargo.toml
src/commands/make.rs

change visibility to be position independent

---

src/commands/invite_users.rs
src/github/rest.rs

add teams parameter to invite

---

src/commands/branch.rs
src/commands/branch_unprotect.rs
src/commands/mod.rs
src/github/rest.rs

add ability to unprotect branches

---

src/commands/status.rs

add quiet option to gut status

---

src/commands/status.rs

Closes #151 
Fixes the issue of being _too_ quiet.

consider origin in quiet status

---

Cargo.lock
Cargo.toml

switch to vendored ssl
